version: '3.9'

services:
  backend:
    image: shivamdubeyagra/todo-app-backend:8fd0f01ecd8432f68df81d11066f4eb1ae258ee5
    container_name: http-backend
    ports:
      -"4000:4000"
    environment:
      - MONGO_URI: mongodb://mongo:27017/turbo-db
      - PORT: 4000
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:7
    container_name: mongo-db
    volumes:
      -mongo_data:/data/db
    restart: unless-stopped
volumes:
  mongo_data
